apiVersion: v1
kind: Service
metadata:
  name: k8sdemohelm
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: k8sdemohelm
